"""initial schema

Revision ID: 5d338ec84d26
Revises: 
Create Date: 2026-09-04 08:11:51.018484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d338ec84d26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('entry_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'seq', name='uq_audit_tenant_seq')
    )
    with op.batch_alter_table('audit_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_entries_entry_hash'), ['entry_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_entries_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_entries_trace_id'), ['trace_id'], unique=False)
        batch_op.create_index('ix_audit_tenant_seq', ['tenant_id', 'seq'], unique=False)

    op.create_table('decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('signals', sa.JSON(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decisions_decision'), ['decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_decisions_tenant_time', ['tenant_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_decisions_trace_id'), ['trace_id'], unique=False)

    op.create_table('drift_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('severity', sa.Float(), nullable=False),
    sa.Column('per_feature', sa.JSON(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drift_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drift_snapshots_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drift_snapshots_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_drift_tenant_model_time', ['tenant_id', 'model_id', 'computed_at'], unique=False)

    op.create_table('feature_samples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feature_samples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feature_samples_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feature_samples_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_samples_tenant_model', ['tenant_id', 'model_id', 'created_at'], unique=False)

    op.create_table('policy_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('condition', sa.Text(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_rules_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_rules_tenant', ['tenant_id', 'enabled'], unique=False)

    op.create_table('tenants',
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenants_api_key_hash'), ['api_key_hash'], unique=False)

    op.create_table('models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('baseline', sa.JSON(), nullable=True),
    sa.Column('baseline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'model_id', name='uq_models_tenant_model')
    )
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_models_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_models_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_models_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_models_model_id'))

    op.drop_table('models')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_api_key_hash'))

    op.drop_table('tenants')
    with op.batch_alter_table('policy_rules', schema=None) as batch_op:
        batch_op.drop_index('ix_rules_tenant')
        batch_op.drop_index(batch_op.f('ix_policy_rules_tenant_id'))

    op.drop_table('policy_rules')
    with op.batch_alter_table('feature_samples', schema=None) as batch_op:
        batch_op.drop_index('ix_samples_tenant_model')
        batch_op.drop_index(batch_op.f('ix_feature_samples_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_feature_samples_model_id'))

    op.drop_table('feature_samples')
    with op.batch_alter_table('drift_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_drift_tenant_model_time')
        batch_op.drop_index(batch_op.f('ix_drift_snapshots_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_drift_snapshots_model_id'))

    op.drop_table('drift_snapshots')
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decisions_trace_id'))
        batch_op.drop_index('ix_decisions_tenant_time')
        batch_op.drop_index(batch_op.f('ix_decisions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_decisions_model_id'))
        batch_op.drop_index(batch_op.f('ix_decisions_decision'))

    op.drop_table('decisions')
    with op.batch_alter_table('audit_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_tenant_seq')
        batch_op.drop_index(batch_op.f('ix_audit_entries_trace_id'))
        batch_op.drop_index(batch_op.f('ix_audit_entries_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_audit_entries_entry_hash'))

    op.drop_table('audit_entries')
    # ### end Alembic commands ###

